export default [
  "WPS Copilot: uw AI-copiloot voor elke documenttaak",
  "Van concept tot analyse en presentatie – hoe WPS Copilot opnieuw definieert wat een kantoorpakket kan betekenen voor 500 miljoen gebruikers.",
  "Lin Wei",
  "VP, WPS AI Product",
  "WPS Copilot AI",
  "WPS Copilot",
  "AI",
  "WPS Copilot is geen add-on – het is de kern van hoe WPS Office in 2026 werkt. Direct ingebed in Writer, Spreadsheet, Presentation en PDF begrijpt Copilot het document waaraan u werkt en handelt ernaar: alinea's herschrijven, formules genereren, presentaties bouwen en honderdpagina-rapporten samenvatten – allemaal zonder van app te wisselen.",
  "De filosofie is eenvoudig: uw AI-assistent hoort te leven waar uw werk plaatsvindt. Dat betekent geen kopiëren en plakken tussen een chatvenster en een document, geen verloren context. Wanneer Copilot een alinea in Writer herschrijft, leest het de omliggende secties om toon en argumentatie te behouden. Wanneer het een grafiek in Spreadsheet genereert, leest het de kolomkoppen en gegevenstypen om het meest geschikte grafiektype te kiezen en de juiste labels toe te passen.",
  "Enterprise-teams die WPS 365 gebruiken, kunnen Copilot configureren om on-premise LLM-endpoints te gebruiken voor strikte gegevenslocatie. In de modus \"zero data retention\" wordt inhoud die naar Copilot wordt gestuurd nooit gelogd nadat het antwoord is teruggegeven – cruciaal voor gereguleerde sectoren zoals financiën, gezondheidszorg en juridische diensten.",
  "Onze interne gegevens tonen aan dat WPS 365 Pro-gebruikers met actieve Copilot eerste concepten 3x sneller afronden en documenten in een derde van de tijd opmaken met één klik op Beautify. De ROI loopt op: minder tijd aan opmaak en concepten betekent meer tijd voor werk dat echt menselijk oordeel vereist.",
  "WPS Copilot is vandaag beschikbaar voor WPS 365 Pro-abonnees op Windows, macOS, iOS, Android en web. Het gratis niveau omvat 5 Copilot-sessies per dag – genoeg om het verschil te ervaren vóór u upgradet.",
  "Grenzeloos samenwerken met WPS Web",
  "Realtime co-editing, live cursors en commentaarthreads – WPS Web brengt uw hele team samen in één gedeelde werkruimte, op elk apparaat.",
  "Sarah Chen",
  "Product Lead, WPS Web",
  "Teamsamenwerking op WPS Web",
  "Samenwerking",
  "WPS Web",
  "Cloud",
  "De aard van kantoorwerk is veranderd. Teams zitten niet meer in dezelfde ruimte, tijdzone of zelfs hetzelfde continent. WPS Web is gebouwd voor deze realiteit: een volledig kantoorpakket dat in de browser draait, op alle apparaten synchroniseert en meerdere mensen hetzelfde document tegelijk laat bewerken – met wijzigingen in minder dan 200 milliseconden.",
  "De samenwerkingslaag van WPS Web is gebouwd op WPS Drive, de cloudopslagdienst die elk document automatisch gesynchroniseerd houdt. Wanneer u op uw telefoon een bestand opent dat een collega net op de laptop heeft bijgewerkt, ziet u direct de nieuwste versie. Geen \"mail de laatste versie\", geen \"wie heeft het masterbestand\" – er is één document, altijd actueel.",
  "Commentaarthreads en @mentions houden gesprekken gekoppeld aan de relevante inhoud. Selecteer tekst, plaats een opmerking, vermeld een collega en zij ontvangen een e-mailmelding met een link die direct naar het commentaar scrollt. Opgeloste threads worden gearchiveerd maar blijven doorzoekbaar – de volledige beslissingsgeschiedenis blijft bij het document.",
  "Machtigingsinstellingen laten eigenaren per link of per gebruiker \"alleen bekijken\", \"commentaar\" of \"bewerken\" instellen. Spreadsheet-eigenaren kunnen bovendien beperken welke kolommen of rijen specifieke editors mogen wijzigen – essentieel voor gedeelde budgetten, HR-dossiers of projecttrackers waarbij sommige gegevens beschermd moeten blijven.",
  "WPS Web is beschikbaar voor alle WPS-gebruikers – Free-accounts kunnen bekijken en reageren, Pro-accounts krijgen volledige bewerking en samenwerking. Geen installatie vereist: open documenten op web.wps.com vanuit elke moderne browser op elk besturingssysteem.",
  "Smart Slides: van outline naar presentatie in minuten",
  "AI genereert structuur, kiest een thema, schrijft spreeknotities en verfijnt dia voor dia – allemaal in WPS Presentation.",
  "Marcus Holt",
  "GM, WPS Presentation",
  "WPS Presentation Smart Slides",
  "Smart Slides",
  "Presentatie",
  "Een presentatie maken betekende vroeger uren van blanco-pagina-angst: een thema kiezen, dia's ordenen, spreeknotities schrijven, grafieken invoegen. Smart Slides comprimeert dit proces tot minuten. Plak een tekstoutline of documentbriefing, kies toon en visuele stijl, en WPS Presentation bouwt de volledige presentatie – met lay-outs, grafieken waar gegevens worden gedetecteerd en spreeknotities voor elke dia.",
  "De AI is geen eenmalige generator. U behoudt gedurende het hele proces de volledige controle. Genereer individuele dia's opnieuw zonder de rest van de presentatie aan te raken. Wissel het volledige thema met één klik en alle elementen – lettertypen, kleuren, achtergronden – passen zich automatisch aan het nieuwe palet aan. Het resultaat ziet eruit alsof een ontwerper uren heeft gewerkt, omdat het systeem duizenden professionele ontwerpregels heeft geïnternaliseerd.",
  "Smart Slides integreert natuurlijk in bestaande workflows. Plak een vergadersamenvatting en krijg een stakeholder-update-presentatie. Plak een onderzoeksartikel en krijg een conferentiepresentatie. Plak een salesbriefing en krijg een pitchdeck met concurrentievergelijkingen en prijstabellen – consistent opgemaakt, klaar om te presenteren.",
  "De output is een standaard PPTX-bestand, volledig bewerkbaar in Microsoft PowerPoint 2016-2025 zonder layoutverlies. Exporteer naar PDF, MP4-video of web-embed HTML voor maximale flexibiliteit. De mobiele app ondersteunt laserpointermodus en realtime Q&A met het publiek via een QR-gekoppelde sessie tijdens live presentaties.",
  "Smart Slides is beschikbaar voor WPS 365 Pro en hoger op Windows, macOS en WPS Web. Het gratis niveau staat tot 3 Smart Slides-generaties per maand toe, zodat u het kunt proberen vóór u abonneert.",
  "Lange PDF's met één klik samenvatten met WPS AI",
  "Stel vragen over honderdpagina-rapporten, krijg opsommingssamenvattingen en exporteer kernpunten naar Word – allemaal zonder WPS te verlaten.",
  "WPS Product Team",
  "WPS PDF",
  "WPS PDF AI Summarize",
  "PDF",
  "AI Summarize",
  "Copilot",
  "Het lezen van een rapport van 150 pagina's zou geen 150 minuten moeten duren. WPS AI Summarize verandert dit: open een PDF, klik op AI Summarize en kies uw uitvoerformaat – opsomming voor snel scannen, executive brief voor managementreview of interactieve Q&A voor diepgaande analyse. Het hele proces duurt minder dan 30 seconden.",
  "Document Q&A is bijzonder krachtig voor onderzoek en compliance. Vraag: \"Wat zijn de belangrijkste risicofactoren in sectie 4?\" of \"Bevat dit contract een beperking van aansprakelijkheid, en op welke pagina?\" WPS AI antwoordt met paginaverwijzingen, zodat u elke bewering in context kunt verifiëren.",
  "Citaten zijn ingebed in elke samenvatting. Elke opsomming of alinea is voorzien van het paginanummer waaruit deze is gehaald. Bij export naar Word worden citaten overgenomen als voetnoten of inline verwijzingen – klaar voor literatuuronderzoek of audittrail.",
  "De AI-leesengine ondersteunt gescande PDF's via ingebouwde OCR. Zelfs een met de telefoon gefotografeerd document kan worden verwerkt, samengevat en met volledige nauwkeurigheid doorzocht. De OCR-engine ondersteunt Latijn, CJK (Chinees, Japans, Koreaans), Arabisch en Devanagari.",
  "WPS 365 Pro-abonnees krijgen onbeperkte AI PDF-samenvattingen en Q&A-sessies. Het gratis niveau omvat 5 sessies per dag – voldoende voor incidenteel gebruik. Batchverwerking (alle PDF's in een map 's nachts samenvatten) is beschikbaar als enterprise-functie op WPS 365 Team en hoger.",
  "WPS 365 Enterprise: ISO 27001, GDPR en gegevenslocatie voor gereguleerde sectoren",
  "Hoe WPS Office voldoet aan de beveiligings- en compliancestandaarden die wereldwijde ondernemingen in financiën, gezondheidszorg, overheid en juridische diensten vereisen.",
  "WPS Trust Center",
  "Beveiliging & compliance",
  "WPS Enterprise Security",
  "Enterprise",
  "Beveiliging",
  "Compliance",
  "GDPR",
  "Toen Kingsoft WPS 365 Enterprise ging bouwen, was de opdracht duidelijk: beveiliging mag geen bijzaak of add-on zijn. Het moet vanaf de basis zijn ontworpen. Vandaag beschikt WPS Office over certificeringen onder ISO/IEC 27001, ISO/IEC 27018, ISO/IEC 27701 en ISO/IEC 20000.",
  "Alle bestanden in WPS Drive worden at rest versleuteld met AES-256. Gegevens onderweg tussen apparaten en WPS-servers worden beschermd met TLS 1.3. Enterprise-klanten kunnen eigen sleutels meebrengen voor maximale controle.",
  "Gegevenslocatie is een first-class functie in WPS 365 Enterprise. Organisaties kunnen specificeren in welke regio hun gegevens worden opgeslagen, en gereguleerde teams kunnen private cloud of on-premise implementaties kiezen.",
  "WPS Copilot in Enterprise-modus biedt een zero-data-retention-optie – cruciaal voor advocatenkantoren, financieel adviseurs en zorgverleners die klantgegevens niet in externe systemen mogen laten bestaan.",
  "Hoe wereldwijde teams in 40 landen standaardiseren op WPS 365",
  "Een kijkje in de digitale werkplektransformatie van organisaties die WPS 365 als primaire productiviteitsplatform kozen.",
  "WPS Customer Success",
  "Enterprise-accounts",
  "Wereldwijd team gebruikt WPS",
  "Klantverhalen",
  "Digitale transformatie",
  "Wanneer een multinationale organisatie haar productiviteitsplatform wil standaardiseren, zijn de uitdagingen groot: verschillende besturingssystemen, legacy-documentformaten en strenge IT-controle-eisen. WPS 365 Enterprise is ontworpen om deze tegelijk op te lossen.",
  "Microsoft Office-compatibiliteit staat centraal. DOCX-, XLSX- en PPTX-bestanden gaan tussen WPS en Microsoft Office met minimaal opmaakverlies – migratie wordt minder verstorend voor teams en partners.",
  "Beheerders kunnen WPS 365 via MDM-tools uitrollen met vooraf geconfigureerd beleid voor formaten, sjablonen, AI-gebruik en cloudopslaglimieten.",
  "Gedeelde sjabloonbibliotheken en realtime samenwerking helpen teams off-brand output en e-mailgebaseerde versiebeheer te verminderen en de uitrol over regio's te versnellen.",
  "WPS Template Marketplace bereikt 100.000 professionele designs",
  "Van cv-sjablonen tot pitchdecks en regionale feestdagenthema's – hoe het WPS-sjabloonecosysteem groeide om 500 miljoen gebruikers te bedienen.",
  "WPS Corporate",
  "Newsroom",
  "WPS Template Marketplace",
  "Sjablonen",
  "Mijlpaal",
  "Creator Economy",
  "De WPS Template Marketplace heeft de grens van 100.000 gepubliceerde designs overschreden – een mijlpaal die zowel de schaal van de WPS-gebruikersgemeenschap als de groeiende professionalisering van sjablooncreatie als vak weerspiegelt.",
  "Community-makers kunnen betaalde pakketten publiceren met omzetdeling, terwijl ondernemingen goedgekeurde private sjablooncatalogi voor hun organisaties kunnen samenstellen.",
  "Officiële sjablonen worden getest op Windows, macOS, iOS, Android en web voor consistente weergave.",
  "De volgende fase van de marketplace introduceert AI-ondersteunde sjabloonpersonalisatie, zodat gebruikers sneller sjablonen vinden en aanpassen.",
  "Volledige kantoorfunctionaliteit in uw zak: de AI-update van WPS Mobile",
  "Camerascan met OCR, AI Rewrite, Smart Slides op mobiel – de WPS Mobile 2026-update brengt desktopklasse-AI naar iPhone en Android.",
  "Mobile Team",
  "WPS Mobile",
  "WPS Mobile AI-functies",
  "Mobiel",
  "OCR",
  "WPS App",
  "WPS Mobile 2026 brengt desktopklasse-AI-ervaringen naar smartphones en tablets en maakt mobiel een eersteklas werkapparaat.",
  "Camera Scan with AI zet gedrukte pagina's of whiteboards om in bewerkbare documenten met OCR en behoud van lay-out.",
  "AI Rewrite en Smart Slides op mobiel helpen gebruikers tekst te herzien of een presentatie te bouwen zonder een laptop te openen.",
  "Hetzelfde WPS 365-abonnement dekt desktop, web en mobiel en houdt documenten, sjablonen en AI-toegang consistent op alle apparaten.",
  "Toegankelijkheid",
  "Screenreader-ondersteuning, hoog contrast en toetsenbordnavigatie in WPS-apps.",
  "WPS ondersteunt Windows Narrator, macOS VoiceOver en gangbare screenreaders op het web.",
  "Schakel hoogcontrastthema's in via Instellingen → Toegankelijkheid.",
  "Alle primaire acties zijn bereikbaar via sneltoetsen die in Help zijn gedocumenteerd.",
  "Account & facturering",
  "Beheer abonnement, facturen en betaalmethoden voor WPS 365.",
  "Meld u aan op account.wps.ai om uw plan en verlengingsdatum te bekijken.",
  "Upgrade of downgrade via Plannen & facturering zonder documenten te verliezen.",
  "Enterprise-beheerders beheren licenties vanuit het Admin Center.",
  "AI Assistant",
  "App-overstijgend AI-paneel voor schrijven, samenvatten en vertalen.",
  "Open het AI-paneel via het lint of druk Alt+I in ondersteunde apps.",
  "Contextbewuste suggesties gebruiken de huidige documentselectie.",
  "Pro-abonnees krijgen hogere daglimieten en prioriteitsmodellen.",
  "Cloudsync & WPS Drive",
  "Bestanden opslaan, synchroniseren en delen op alle apparaten met WPS Drive.",
  "Bestanden in WPS Drive synchroniseren automatisch wanneer u bent aangemeld.",
  "Deel links met bekijk- of bewerkrechten en optionele vervaldatum.",
  "Versiegeschiedenis bewaart de laatste 30 dagen op Pro-plannen.",
  "Realtime samenwerking",
  "Bewerk documenten, spreadsheets en dia's samen met teamleden.",
  "Nodig medewerkers uit via e-mail of link via de knop Delen.",
  "Zie live cursors en opmerkingen in Writer, Sheets en Presentation.",
  "Volg wijzigingen en accepteer of weiger bewerkingen in reviewmodus.",
  "Excel-sjablonen",
  "Budget-, kalender- en projectsjablonen voor WPS Spreadsheets.",
  "Blader door sjablonen via het dialoogvenster Nieuw bestand of Template Center.",
  "AI kan voorbeeldgegevens invullen op basis van uw branche en regio.",
  "Exporteer sjablonen naar .xlsx of deel ze in uw teambibliotheek.",
  "Formulieren & enquêtes",
  "Maak formulieren en verzamel antwoorden gekoppeld aan Sheets.",
  "Bouw formulieren met meerdere vraagtypen en logische vertakking.",
  "Antwoorden synchroniseren naar een spreadsheet voor grafieken en filters.",
  "Embed formulieren op websites of deel via QR-code.",
  "WPS mobiele apps",
  "iOS- en Android-apps voor documenten onderweg.",
  "Bewerk, scan en onderteken PDF's vanaf uw telefoon of tablet.",
  "Offline-modus cachet recente bestanden voor bewerking zonder netwerk.",
  "Scan to PDF gebruikt on-device OCR voor tekstextractie.",
  "PDF converteren & exporteren",
  "Converteer PDF naar Word, Excel, PPT en afbeeldingen.",
  "Sleep een PDF naar WPS PDF of gebruik online tools op wps.ai.",
  "Batchconversie is beschikbaar op Pro- en Business-plannen.",
  "OCR draait automatisch op gescande pagina's wanneer gedetecteerd.",
  "PDF bewerken & annoteren",
  "Bewerk tekst, voeg samen, splits, onderteken en annoteer PDF-bestanden.",
  "Voeg markeringen, stempels en vrije tekeningen toe.",
  "Bewerk tekst in native PDF's zonder te converteren naar Word.",
  "Voeg pagina's samen en herschik ze via het deelvenster Paginaminiaturen.",
  "Presentatiethema's",
  "Designerthema's en lay-outs voor WPS Presentation.",
  "Pas thema's toe via het tabblad Ontwerp; kleuren en lettertypen worden globaal bijgewerkt.",
  "Smart Slides stelt lay-outs voor op basis van diainhoud.",
  "Exporteer naar video of PDF-handouts voor distributie.",
  "Smart Sheets (AI)",
  "AI-formules, analyse en grafiekengeneratie in spreadsheets.",
  "Beschrijf de analyse die u nodig hebt in gewone taal.",
  "Genereer formules met uitleg die u kunt controleren.",
  "Maak dashboards uit geselecteerde bereiken met één klik.",
  "AI-gegenereerde outlines en presentaties uit een korte briefing.",
  "Voer onderwerp, doelgroep en lengte in om een outline te genereren.",
  "Genereer individuele dia's opnieuw zonder de hele presentatie te herbouwen.",
  "Spreeknotities worden automatisch voor elke dia opgesteld.",
  "Template Center",
  "CV-, contract- en presentatiesjablonen om te downloaden.",
  "Duizenden gratis en premium sjablonen in alle categorieën.",
  "Voorbeeld vóór download; Pro ontgrendelt commerciële licenties.",
  "Bewaar favorieten in uw cloudbibliotheek voor snel hergebruik.",
  "WPS 365",
  "Abonnementsbundel met AI, cloudopslag en premium sjablonen.",
  "Inclusief Writer, Spreadsheets, Presentation, PDF en AI-tegoed.",
  "Kies Personal, Family of Business met facturering per licentie.",
  "Vergelijk plannen op de prijspagina of in de in-app upgrade-flow.",
  "Volledige PDF-toolkit: lezen, bewerken, converteren, ondertekenen en beschermen.",
  "Open PDF's vanuit Explorer, Finder of via drag-and-drop in WPS.",
  "AI Summarize haalt kernpunten op met paginacitaties.",
  "Bescherm met wachtwoord of redigeer gevoelige delen vóór u deelt.",
  "WPS Presentation",
  "Maak dia's, animaties en exporteer naar video of PDF.",
  "Compatibel met .pptx; co-presenteer met Teams en Zoom.",
  "Morph-overgangen en 3D-modellen op ondersteunde builds.",
  "Neem diavoorstelling op met voice-over voor asynchroon delen.",
  "WPS Spreadsheets",
  "Spreadsheets met formules, draaitabellen en gegevenstools.",
  "Ondersteunt XLSX, CSV en grote datasets met performancemodus.",
  "Draaitabellen, voorwaardelijke opmaak en gegevensvalidatie ingebouwd.",
  "Verbind met externe gegevensbronnen op Business-plannen.",
  "WPS Writer",
  "Tekstverwerking met AI co-writing, stijlen en mail merge.",
  "Maak en bewerk DOCX met volledige compatibiliteit met Microsoft Word.",
  "AI Co-writing biedt inline suggesties en toonaanpassingen.",
  "Mail merge koppelt aan Sheets of CSV voor bulkbrieven.",
  "AI Translate",
  "Vertaal documenten en selecties in meer dan 100 talen.",
  "Vertaal volledige documenten met behoud van lay-out waar mogelijk.",
  "Woordenlijstondersteuning voor consistente terminologie in enterprise.",
  "Naast-elkaar-weergave vergelijkt bron- en doelalinea's.",
  "WPS Office-overzicht",
  "Een compleet kantoorpakket voor documenten, spreadsheets, presentaties, PDF, cloud en AI-werk.",
  "WPS Office brengt Writer, Spreadsheets, Presentation, PDF, cloudopslag, sjablonen en AI-ondersteuning samen in één werkruimte.",
  "De suite is ontworpen voor persoonlijke productiviteit, onderwijs en zakelijke samenwerking op desktop, web en mobiel.",
  "Begin met een leeg bestand, een sjabloon of een bestaand Microsoft Office-document en houd opmaak teamoverstijgend compatibel.",
  "AI-ondersteuning voor concepten, herschrijven, samenvatten, inzichten extraheren en dia's maken.",
  "WPS Copilot werkt binnen WPS-apps, zodat u om hulp kunt vragen zonder inhoud naar een aparte tool te verplaatsen.",
  "Het kan geselecteerde alinea's herschrijven, PDF's samenvatten, spreadsheetgegevens uitleggen en outlines omzetten in presentatieconcepten.",
  "Enterprise-plannen kunnen beheerderscontroles, gebruikslimieten en gegevensbeleid toepassen voor beheerde AI-adoptie.",
  "Installatie en instellingen",
  "Download WPS, meld u aan, kies standaardinstellingen en bereid apps voor op dagelijks werk.",
  "Download het installatieprogramma voor Windows of macOS, of installeer de mobiele app uit de officiële app store.",
  "Na installatie meldt u zich aan om cloudbestanden, sjablonen en abonnementsstatus op alle apparaten te synchroniseren.",
  "U kunt WPS tijdens installatie of via systeeminstellingen als standaardapp voor Office- en PDF-formaten instellen.",
  "Systeemvereisten",
  "Ondersteunde besturingssystemen, browsers, opslag en apparaataanbevelingen.",
  "WPS ondersteunt actuele Windows-, macOS-, iOS- en Android-versies en moderne webbrowsers voor WPS Web.",
  "Voor grote spreadsheets of AI-intensieve workflows: gebruik een apparaat met voldoende geheugen en een stabiele netwerkverbinding.",
  "Houd WPS bijgewerkt voor compatibiliteitsverbeteringen, beveiligingspatches en nieuwe AI-mogelijkheden.",
  "Accountaanmelding",
  "Meld u aan, herstel toegang en beheer accountbeveiliging voor WPS-diensten.",
  "Gebruik uw e-mail, telefoonnummer of ondersteund extern account om u aan te melden bij WPS.",
  "Bij een vergeten wachtwoord start u herstel vanaf de aanmeldpagina en verifieert u e-mail of telefoon.",
  "Schakel waar beschikbaar sterkere accountbescherming in, vooral in gedeelde zakelijke omgevingen.",
  "Abonnementsplannen",
  "Vergelijk mogelijkheden van Free-, Pro-, Family- en Business-plannen.",
  "Free-gebruikers kunnen gangbare bestanden bewerken en geselecteerde AI- en cloudfuncties met daglimieten proberen.",
  "Pro-plannen ontgrendelen hogere AI-limieten, premium PDF-tools, meer cloudopslag en geavanceerde sjablonen.",
  "Business-plannen voegen beheer, teamfacturering, beveiligingscontroles en gecentraliseerde uitrolopties toe.",
  "Versiegeschiedenis",
  "Herstel eerdere bestandsversies en begrijp hoe cloudopslag wordt bijgehouden.",
  "Bestanden in WPS Drive kunnen eerdere versies bewaren, zodat u per ongeluk bewerkingen kunt terugdraaien.",
  "Versiebewaring hangt af van uw plan en werkruimtebeleid.",
  "Voor teambestanden: combineer versiegeschiedenis met machtigingen en opmerkingen voor traceerbare samenwerking.",
  "Beveiliging en privacy",
  "Bescherm bestanden, beheer delen en begrijp WPS-privacywaarborgen.",
  "WPS biedt machtigingscontroles, wachtwoordbeveiliging voor PDF's en veilige clouddeelopties.",
  "Business-beheerders kunnen toegangsbeleid, gebruikerslicenties en beveiligingsinstellingen op organisatieniveau beheren.",
  "Controleer privacy-instellingen vóór u gevoelige bestanden deelt of AI-functies inschakelt in gereguleerde workflows.",
  "Office-compatibiliteit",
  "Open, bewerk en exporteer Microsoft Office-bestanden met lay-outgetrouwheid.",
  "WPS ondersteunt gangbare DOCX-, XLSX-, PPTX-, PDF-, CSV- en sjabloonformaten voor dagelijks kantoorwerk.",
  "Lettertypen, grafieken, formules, opmerkingen en wijzigingen bijhouden blijven in de meeste workflows behouden.",
  "Bij extern delen: exporteer naar PDF voor vaste lay-out of behoud native Office-formaten voor bewerkbare samenwerking.",
  "PDF-compatibiliteit",
  "Lees, annoteer, converteer, bescherm en exporteer PDF's op alle apparaten.",
  "WPS PDF ondersteunt standaard-PDF's, gescande documenten met OCR, annotaties, handtekeningen en pagina-acties.",
  "Conversietools helpen inhoud tussen PDF, Word, Excel, PowerPoint en afbeeldingen te verplaatsen.",
  "Gebruik wachtwoordbeveiliging en redactie vóór u documenten met privé-informatie verstuurt.",
  "FAQ: account en facturering",
  "Veelgestelde antwoorden over aanmelding, abonnementen, facturen, verlengingen en terugbetalingen.",
  "Als uw abonnement na aankoop niet verschijnt, meld u aan met het account dat bij checkout is gebruikt en vernieuw de planstatus.",
  "Facturen en betaalmethoden kunt u beheren vanuit het accountcentrum waar ondersteund.",
  "Voor teamplannen: neem contact op met de werkruimtebeheerder vóór u licenties of factureringseigenaarschap wijzigt.",
  "FAQ: bestanden en formaten",
  "Antwoorden over bestanden openen, opmaak behouden, PDF's converteren en documenten herstellen.",
  "Als een bestand na openen anders oogt, controleer ontbrekende lettertypen, ingesloten objecten of geavanceerde macro's uit de bronapp.",
  "Gebruik PDF-export wanneer de lay-out vast moet blijven voor print of externe review.",
  "Cloud-opgeslagen bestanden kunnen vaak worden hersteld uit recente bestanden, prullenbak of versiegeschiedenis, afhankelijk van het plan.",
]
